Домашнє завдання №1

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
a = np.random.randint(1, 11, (5,5))
print(a)

[[ 7 10  6  2 10]
 [ 7  9  4  2  8]
 [ 3  3  6  5  9]
 [10  8  3  5  1]
 [ 3  3  9  1  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [6]:
a = np.random.rand(4, 4)
print(a)

[[0.35448893 0.62348182 0.25158109 0.20567579]
 [0.51100877 0.36949712 0.22480539 0.86426348]
 [0.67691192 0.03815413 0.42832246 0.20885283]
 [0.48009991 0.53849911 0.56553487 0.62994907]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [7]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [6 2 2 9 6]
b =  [8 4 9 5 8]
a + b =  [14  6 11 14 14]
a - b =  [-2 -2 -7  4 -2]
a * b =  [48  8 18 45 48]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [11]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [6 6 6 9 4 1 8]
b =  [ 3 10  9  3  5  2  9]
Скалярний добуток векторів дорівнює: 253


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [14]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 3))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[7 1]
 [3 5]]
b =  [[3 1 1]
 [1 2 1]]
Результат множення матриць:
[[22  9  8]
 [14 13  8]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю. (Обернена матриця існує тільки для квадратних матриць, для яких детермінант не дорівнює нулю)

In [21]:
a = np.random.randint(1, 11, size=(3, 3))
print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)


Вихідна матриця:
[[3 1 3]
 [5 8 7]
 [6 4 1]]
Обернена матриця:
[[ 0.18691589 -0.10280374  0.1588785 ]
 [-0.34579439  0.14018692  0.05607477]
 [ 0.26168224  0.05607477 -0.17757009]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [23]:
a = np.random.rand(4, 4)
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[0.87298873 0.32313631 0.84631268 0.70152019]
 [0.92968705 0.08546864 0.14092307 0.76525695]
 [0.12001872 0.22090021 0.28490696 0.32351804]
 [0.68992537 0.84135905 0.93096108 0.28223114]]
Транспонована матриця:
[[0.87298873 0.92968705 0.12001872 0.68992537]
 [0.32313631 0.08546864 0.22090021 0.84135905]
 [0.84631268 0.14092307 0.28490696 0.93096108]
 [0.70152019 0.76525695 0.32351804 0.28223114]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [26]:
matr = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, size=4)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[8 3 7 6]
 [9 8 8 7]
 [9 7 3 6]]
Вектор:
[9 2 3 3]
Результат множення матриці на вектор:
[117 142 122]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [27]:
matr = np.random.rand(2, 3)
vect = np.random.rand(3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.69817495 0.66957257 0.0633264 ]
 [0.94132088 0.70192663 0.98405776]]
Вектор:
[0.97630631 0.55499514 0.06980454]
Результат множення матриці на вектор:
[1.0576626  1.37727509]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [31]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Поелементне множення через multiply:")
result = np.multiply(a, b)
print(result)
print("Поелементне множення через *:")
print(a*b)

Перша матриця:
[[5 4]
 [1 6]]
Друга матриця:
[[6 4]
 [1 8]]
Поелементне множення через multiply:
[[30 16]
 [ 1 48]]
Поелементне множення через *:
[[30 16]
 [ 1 48]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [30]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Добуток матриць:")
result = np.dot(a, b)
print(result)

Перша матриця:
[[5 8]
 [1 5]]
Друга матриця:
[[10  4]
 [ 6 10]]
Добуток матриць:
[[ 98 100]
 [ 40  54]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [32]:
a = np.random.randint(1, 101, size=(5, 5))
sum_a = np.sum(a)
print("Матриця")
print(a)
print("Сума елементів матриці:")
print(sum_a)

Матриця
[[33 35 46 98  3]
 [35 26 67 92 30]
 [15 56 56 68 26]
 [64 95 21  6  2]
 [66 13 91  9 42]]
Сума елементів матриці:
1095


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [33]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

result = a - b
print("Різниця матриць:")
print(result)

Перша матриця:
[[ 5  3  5  7]
 [ 9  5  3  2]
 [ 1  7  6  6]
 [ 6  9 10  9]]
Друга матриця:
[[ 6  2 10  3]
 [ 9  4  7  3]
 [ 7  1  7  6]
 [ 2  9  8  5]]
Різниця матриць:
[[-1  1 -5  4]
 [ 0  1 -4 -1]
 [-6  6 -1  0]
 [ 4  0  2  4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [34]:
a = np.random.rand(3, 3)
print("Матриця:")
print(a)

# Обчислення сум елементів кожного рядка матриці
row_sums = a.sum(axis=1)

# Перетворення одновимірного масиву на вектор-стовпчик
col_vec = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(col_vec)

Матриця:
[[0.93691243 0.87759296 0.8300773 ]
 [0.10116688 0.39740299 0.30359529]
 [0.44538679 0.20820476 0.64165348]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[2.64458269]
 [0.80216515]
 [1.29524503]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [35]:
a = np.random.randint(1, 11, size=(3, 4))
print("Матриця:")
print(a)

print("Квадрати значень матриці:")
squares = np.power(a, 2)
print(squares)

Матриця:
[[ 2  3  9 10]
 [ 8  4  9  7]
 [ 6  8  8  9]]
Квадрати значень матриці:
[[  4   9  81 100]
 [ 64  16  81  49]
 [ 36  64  64  81]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [38]:
vect = np.random.randint(1, 50, size=4)
print("Вихідний вектор", vect)

sqrt_vect = np.sqrt(vect)
print("Вектор з квадратими коренями:", sqrt_vect)

Вихідний вектор [10 20 18 19]
Вектор з квадратими коренями: [3.16227766 4.47213595 4.24264069 4.35889894]
